### ISSUE TITLE
Is EntityFramework.Extended Support MySql And Oracle?

### ISSUE THREAD

**Issue by kinshines** [loresoft/EntityFramework.Extended#163]
I switch my database from SQL Server to MySql,and it can not work with Update method……

**Comment by djechelon** [comment]
+1

As discussed in #51 the implementation of EF.E is tailored to SQL Server dialect. Multiple PRs have been made but as I have highlighted there are two missing parts: choice between `SqlServerBatchRunner` and `MySqlBatchRunner` according to the `ObjectContext.Database.Connection` instance.

I pray @pwelter34 to resume work on this project :cry:

**Comment by pwelter34** [comment]
MySqlBatchRunner merged.

**Comment by Arthur-Z** [comment]
support oracle?

**Comment by djechelon** [comment]
Not yet Oracle. Somebody needs to implement the proper providers like for MysqlBatchRunner
